### ISSUE TITLE
Implement software band-pass filter

### ISSUE THREAD

**Issue by pepijndevos** [pepijndevos/accessibletuner#2]
This will increase the reliability of tuning hopefully, but requires a lot of changes to the code.
The sampling frequency needs to be decreased to reasonable values to be able to construct reasonable filters.
The code also needs to be converted to using signed integers throughout.
Some work has been done in this area, but nothing that really works.

Ideally the filter is dynamically adjusted to the right frequency, but a lookup table is acceptable I think.

[![Bounty](https://api.bountysource.com/badge/issue?issue_id=50544237)](https://www.bountysource.com/issues/50544237-implement-software-band-pass-filter)

**Comment by brain4d** [comment]
i'm really interested  in your  bounty. I have some experience in mixed-signal pcb design, and firmware development. 
How can i discuss with you in detail?

**Comment by pepijndevos** [comment]
Awesome! Shoot me an email at pepijndevos@gmail.com

**Comment by brain4d** [comment]
i already sent you an email.

**Comment by pepijndevos** [comment]
As of dbe5d09517160fcf41d7a1f8d89856c811fa1d5f this has been implemented by me. So instead I'll award the bounty to @ant0nisk for his work on the 3D printed case.
